<template>
    <div class="container">
        <h1>Settings</h1>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
        <p>Tet</p>
    </div>
</template>
